### ISSUE TITLE
Hardware SPI on Leonardo

### ISSUE THREAD

**Issue by sonik-br** [SukkoPera/PsxNewLib#12]
Hi!
I'm trying to use the hardware ICSP pins on the Leonardo with the PsxControllerHwSpi lib.
No success ...
I'm doing:
PSX > Leonardo ICSP pin
DAT > 1 (MISO)
CLK > 3 (SCK)
CMD > 4 (MOSI)
ATT > 9 (digital pin, not on ICSP)
Also GND and 3.3V...

It's supposed to work on the Leonardo or just on the Uno?

**Comment by SukkoPera** [comment]
It works great on the Leonardo, make sure to use the right pins and 1k pullups.

Also make sure to use the right pin for ATT. I think it's 10 by default, switch pin or change it in the sketch.

**Comment by sonik-br** [comment]
1k pullups in which pins? I'm not good with electronics XD

**Comment by SukkoPera** [comment]
On DAT/MISO at least.

**Comment by SukkoPera** [comment]
![image](https://user-images.githubusercontent.com/1316870/122685070-98800f00-d209-11eb-8643-b600d329134d.png)

This is the correct way to do the connections by the way.

**Comment by sonik-br** [comment]
No luck :(
Even with the 1k pullups on the MISO pin.

I'm powering the psx controller with 3.3v from the arduino. But all other pins are 5v. 
This might be the problem?

**Comment by SukkoPera** [comment]
Well, if all the other pins are 5V you're not driving the controller properly. I know everybody out there does that but it doesn't make me happy.

I'd send you one of my PsxShields to thank you for the collaboration but I see you live in Brazil, which I had a lot of problems shipping to :(.

**Comment by sonik-br** [comment]
Thanks but yeah, postal services here are not reliable.

Something like this would work for the data pins?
https://www.amazon.com/HiLetgo-Channels-Converter-Bi-Directional-3-3V-5V/dp/B07F7W91LC/

I can get some here at the local electronics store for a good price. And it seems foolproof to me :)
The schematic:
https://s3-sa-east-1.amazonaws.com/robocore-lojavirtual/522/Level.Shifter_v1.1.pdf

**Comment by SukkoPera** [comment]
Well, it's the same shifting technique I've used on my shield:
![image](https://user-images.githubusercontent.com/1316870/122802236-6df38c00-d2c5-11eb-901e-ef2890e410fa.png)

As you can see, I have changed the pull-ups to 1k, after measuring a real PSX console. This gave me some more compatibility, but most controllers were also working with 10k.

Besides that, you'd also need a beefier 3.3V regulator. I'm not sure how much current the PSX controller needs, but the 3v3 regulator on most Arduinos is really really weak.

Can you solder SMD stuff?

**Comment by sonik-br** [comment]
No, I can't do SMD stuff.
Controller (guncon) works fine using "bitbang" with 3.3v power and 5v on data pins. 
Serial must be more sensitive to voltage level?

**Comment by SukkoPera** [comment]
Not really, SPI should be more reliable, actually. What do you get if you enable debugging?

I will try sending you a shield, please send me your address by email. I will solder the SMD stuff for you but I have run out of the long pin headers, will you be able to get those yourself and solder them?

Yes, that regulator will be fine.

**Comment by sonik-br** [comment]
Thanks :)

I tested with the DumpButtonsHwSpi example and it wont send anything to the serial debug.
With DUMP_COMMS on PsxNewLib.h it was sending some info to the serial.
 I will have to run it again and copy the results here.

I will also do a quick test with the correct regulator and level shift.

**Comment by SukkoPera** [comment]
That is very weird, you should get some output even if you don't connect your controller... I think. It's been a while since I worked on this lib.

Let me know what shows up with DUMP_COMMS.

**Comment by sonik-br** [comment]
I was testing it right now... properly wired with 3.3v level shift and regulator.
Log starts with no controller connected.
It shows various connect/disconnect. But it was connected all the time.

[Serial LOG.txt](https://github.com/SukkoPera/PsxNewLib/files/6705201/Serial.LOG.txt)

**Comment by sonik-br** [comment]
Done a quick test with DumpButtonsBitBang but this time using the SPI pins. Won't work.
From my understanding the dedicated pins should work as common digital I/O pins.
Starting to think I have a bad board.

**Comment by SukkoPera** [comment]
Yep, it should work if you use the following pin numbers:
```
#define PIN_SPI_MOSI  (16)
#define PIN_SPI_MISO  (14)
#define PIN_SPI_SCK   (15)
```

MOSI goes to CMD and MISO to DAT.

**Comment by sonik-br** [comment]
Great news!
Got another level shifter and now it works!
3.3v on power and data pins to the guncon and using hardware SPI.
Now my other guncon (a thirdy party one) seems to work. It was not even detecting previously when using bitbang.
I will wait for the shield to arrive to test it more.
