### ISSUE TITLE
Multitap buttonPressed

### ISSUE THREAD

**Issue by petanque** [SukkoPera/PsxNewLib#30]
I have tried your devel branch to test multitap and it works as expected over the serial port.
I want to make a joystick like in your master branch but then found that buttonPressed is not part of the devel branch, is this something you plan to add in the future?

**Comment by petanque** [comment]
I found out how it could be added by comparing with the master branch so I'm closing this issue.
Thank you for making this.

**Comment by SukkoPera** [comment]
The function is [still there](https://github.com/SukkoPera/PsxNewLib/blob/a69a65245478bc027150a199c099c780ba7dcb3e/src/PsxPublicTypes.h#L259) but it has been moved to the PsxControllerData class, you don't need to add anything. To learn how to work with the multitap, please see the MultiTapTest example.
