### ISSUE TITLE
Didn't mark `getRightAnalog` as `const`

### ISSUE THREAD

**Issue by RechieKho** [SukkoPera/PsxNewLib#31]
So, on line `1186`, 

```
	boolean getRightAnalog (byte& x, byte& y) {
		x = rx;
		y = ry;

		return analogSticksValid;
	}
```

I believe you forgot to mark `const`.

Since the `getLeftAnalog` marked `const` (on line `1165`),

```
	boolean getLeftAnalog (byte& x, byte& y) const {
		x = lx;
		y = ly;

		return analogSticksValid;
	}
```

So I believe it is a bug.

**Comment by RechieKho** [comment]
Hopefully that one day is today 👌

**Comment by SukkoPera** [comment]
Well yes, with a PR everything is easier :). Thanks a lot!
