### ISSUE TITLE
A0 and A1 as OUTPUT for button press????????

### ISSUE THREAD

**Issue by alphanumericaracters** [SukkoPera/PsxNewLib#6]
Why the analog Pins A0 and A1 are outputs if nothing is conected????

In the 2 examples are setup as outputs. 

I have a N1W320 wireless joystick and doesn't work T.T

Can you iluminate me about the clocks problems???

thnx 4 all.

**Comment by SukkoPera** [comment]
They can be used for LEDs. A1 will light up when a supporter controller is detect, and A0 whenever you press a button.

Unfortunately I don't have a N1W320 controller and I cannot test it. Try enabling debug as described in the docs and see if it helps.

**Comment by alphanumericaracters** [comment]
Ohhhhhh! Now i understand i'll try debug and see whats happen, then (if ti's works) upload you the code.

**Comment by SukkoPera** [comment]
I'm closing this as it is a non-issue. Feel free to add comments if you think it is the case.
