### ISSUE TITLE
Joystick_ does note name a type; did you mean 'Joystick'?

### ISSUE THREAD

**Issue by mhay10** [SukkoPera/PsxNewLib#7]
I am having an issue uploading the PSX2USB sketch to a Sparkfun Arduino Pro Micro because when attempting to upload the sketch I get the following error.
`error: 'Joystick_' does not name a type; did you mean 'Joystick'?`

I have not modified the sketch in any way. What am I doing wrong and how can I fix this?

**Comment by SukkoPera** [comment]
Read the top of the sketch and install the mentioned library.

**Comment by SukkoPera** [comment]
So, fixed? Can we close this?

**Comment by SukkoPera** [comment]
No news, I guess this was solved. Closing.
